# Travis CI Configuration
# https://docs.travis-ci.com
# This file is based on
# TravisCI · koalaman/shellcheck Wiki
# https://github.com/koalaman/shellcheck/wiki/TravisCI

language: bash

## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

matrix:
  fast_finish: true

git:
  depth: 1
  submodules: false

addons:
  apt:
    sources:
    packages:
      - realpath      # Merged to GNU Coreutils in Ubuntu 16.04

before_install:
  - git submodule init 'Linters/GNU Bash Automatic Checking Program for Git Projects' 'Continuous Integration/Utilities for Travis CI'
  # Don't fetch too less history as it will trigger "Server does not allow request for unadvertised object" error
  - git submodule update --depth=30

install:
  - ./"Continuous Integration/Utilities for Travis CI/Setup ShellCheck's Latest Release without Re-building.bash"
  - PATH="${HOME}/Software/shellcheck-stable:${PATH}"
  - shellcheck --version

before_script:
  - ./'Linters/GNU Bash Automatic Checking Program for Git Projects/GNU Bash Automatic Checking Program for Git Projects.bash'

script: true

cache:
  directories:
    - $HOME/Software
