# Travis CI Configuration
# https://docs.travis-ci.com
# This file is based on
# TravisCI · koalaman/shellcheck Wiki
# https://github.com/koalaman/shellcheck/wiki/TravisCI

language: bash

## Use container-based infrastructure for quicker build start-up
sudo: false

## We only support Ubuntu 14.04 and newer
dist: trusty

matrix:
  fast_finish: true

git:
  depth: 1
  submodules: false

addons:
  apt:
    sources:
    packages:
      - realpath      # Merged to GNU Coreutils in Ubuntu 16.04

before_install: true

before_script: true

script:
  #- git ls-files -z \*.bash | xargs --max-args=1 --verbose --null -- shellcheck
  # The following command will be dropped in favor with the above one after Travis CI environment contains ShellCheck >=0.4.5, which fixes the bug that triggers SC2148 even when `shell` directive is used
  - git ls-files -z \*.bash | xargs --max-args=1 --verbose --null -- shellcheck --shell=bash
